[addressbooks]
[[general]]
path = /home/kat/.config/vdirsyncer/contacts/52ad2c31-65bb-a4c7-23c7-beac8c3f48e8/

[general]
debug = no
default_action = list
# These are either strings or comma seperated lists
editor = micro
merge_editor = micro

