include current-theme.conf
font_family        Maple Mono NF CN ExtraLight
font_size 14.0
tab_bar_edge top
tab_bar_margin_width 1.0
tab_bar_margin_height 1.0 1.0
tab_bar_style separator
tab_bar_min_tabs 1
tab_bar_background #eaeaea
background_opacity 1
