[melodicake@disroot]
source        = imaps://melodicake%40disroot.org@disroot.org:993
source-cred-cmd = pass config/melodicake_disroot
outgoing      = smtps://melodicake%40disroot.org@disroot.org:465
outgoing-cred-cmd = pass show config/melodicake_disroot
default       = INBOX
from          = kat cain <melodicake@disroot.org>
cache-headers = true

[lachesis@disroot]
source        = imaps://witnesslachesis@disroot.org@disroot.org:993
source-cred-cmd = pass show config/witnesslachesis_disroot
outgoing      = smtps://witnesslachesis%40disroot.org@disroot.org:465
outgoing-cred-cmd = pass show config/witnesslachesis_disroot
default       = INBOX
from          = kat cain <witnesslachesis@disroot.org>
cache-headers = true
