[melodicake@disroot]
source        = notmuch:///home/kat/.local/mail/melodicake@disroot.org
maildir-store = /home/kat/.local/mail/melodicake@disroot.org
outgoing      = smtps://melodicake%40disroot.org@disroot.org:465
outgoing-cred-cmd = pass show "personal/melodicake_disroot"
default       = INBOX
from          = kat cain <melodicake@disroot.org>
cache-headers = true
check-mail-cmd = mbsync -a && notmuch new
check-mail-timeout = 120s


[lachesis@disroot]
source        = notmuch:///home/kat/.local/mail/witnesslachesis@disroot.org
maildir-store = /home/kat/.local/mail/witnesslachesis@disroot.org
source-cred-cmd = pass show "personal/witnesslachesis_disroot"
outgoing      = smtps://witnesslachesis%40disroot.org@disroot.org:465
outgoing-cred-cmd = pass show "personal/witnesslachesis_disroot"
default       = INBOX
from          = kat cain <witnesslachesis@disroot.org>
cache-headers = true
check-mail-cmd = mbsync -a && notmuch new
check-mail-timeout = 120s
