[general]

[ui]
border-char-vertical="│"
border-char-horizontal="─"
styleset-name=catppuccin-frappe

[statusline]

[viewer]
alternatives=text/plain,text/html

[compose]

[multipart-converters]

[filters]
# half of these are stolen from:
# https://aerc-docs.com/recipes/openers/
text/plain=colorize
text/calendar=calendar
text/html=w3m -T text/html -dump -o display_link_number=1 | colorize
message/delivery-status=colorize
message/rfc822=colorize
.headers=colorize

# glow by charmcli
text/markdown=glow -w 0

# syntax highlighting
application/json=bat -fP -l json
application/xml=bat -fP -l xml
application/x-yaml=bat -fP -l yaml
text/x-diff=bat -fP -l diff

# images
image/*=chafa -f kitty -s $(tput cols)x$(tput lines) -

[openers]
# images
image/* = lximage-qt {}

# audio/video
audio/* = mpv {}
video/* = mpv {}

# spreadsheets/docs
application/vnd.openxmlformats-officedocument.* = libreoffice {}

# copy mailto links to clipboard
x-scheme-handler/mailto = printf '%s' {} | xclip -sel clipboard

# fallback to xdg-open for anything else
* = xdg-open {}

[hooks]

[templates]
