[general]

[ui]
border-char-vertical="│"
border-char-horizontal="─"
styleset-name=catppuccin-frappe

[statusline]

[viewer]

[compose]

[multipart-converters]

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=pandoc -f html -t plain | colorize
.headers=colorize

[openers]

[hooks]

[templates]
