# /etc/sddm.conf
#
# added everything after the "Autologin" section
# mainly to hide nix build users

[Autologin]
Session=Lubuntu

[Users]
# Comma-separated list of shells.
# Users with these shells as their default won't be listed
HideShells=/sbin/nologin

# Comma-separated list of users that should not be listed
HideUsers=
